# Generated by Django 5.2.7 on 2025-10-21 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_operator_alter_bingocard_bingo_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo del API Key', max_length=100)),
                ('key', models.CharField(help_text='API Key pública', max_length=64, unique=True)),
                ('secret_hash', models.CharField(help_text='Hash del secret', max_length=128)),
                ('permission_level', models.CharField(choices=[('read', 'Solo lectura'), ('write', 'Lectura y escritura'), ('admin', 'Administrador')], default='write', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='IPs permitidas (vacío = todas)')),
                ('rate_limit', models.IntegerField(default=100, help_text='Requests por minuto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración', null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='bingo.operator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
