# Generated by Django 5.2.7 on 2025-10-22 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinningPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del patrón (ej: Línea Horizontal)', max_length=100)),
                ('code', models.CharField(help_text='Código único del patrón', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del patrón')),
                ('category', models.CharField(choices=[('classic', 'Clásico'), ('special', 'Especial'), ('custom', 'Personalizado')], default='classic', max_length=20)),
                ('compatible_with', models.CharField(choices=[('all', 'Todos'), ('75', 'Solo 75 bolas'), ('85', 'Solo 85 bolas'), ('90', 'Solo 90 bolas')], default='all', max_length=10)),
                ('pattern_type', models.CharField(help_text='Tipo: horizontal_line, vertical_line, diagonal, full_card, etc.', max_length=50)),
                ('pattern_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del patrón (posiciones, etc.)')),
                ('prize_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador del premio', max_digits=5)),
                ('has_jackpot', models.BooleanField(default=False, help_text='¿Tiene jackpot progresivo?')),
                ('jackpot_max_balls', models.IntegerField(blank=True, help_text='Máximo de bolas para ganar jackpot', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Patrón del sistema (no se puede eliminar)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_patterns', to='bingo.operator')),
            ],
            options={
                'verbose_name': 'Patrón de Victoria',
                'verbose_name_plural': 'Patrones de Victoria',
                'ordering': ['category', 'name'],
            },
        ),
    ]
