# Generated by Django 5.2.7 on 2025-10-22 21:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_winningpattern'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bingocardextended',
            options={'ordering': ['pack', 'card_number']},
        ),
        migrations.AlterUniqueTogether(
            name='bingocardextended',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bingocardextended',
            name='is_reusable',
            field=models.BooleanField(default=True, help_text='Si la carta puede ser reutilizada en múltiples sesiones'),
        ),
        migrations.AddField(
            model_name='bingocardextended',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Número de serie único (ej: OPERA-75-ABC12345-0042)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bingocardextended',
            name='total_sessions',
            field=models.IntegerField(default=0, help_text='Total de sesiones en las que se ha usado'),
        ),
        migrations.AddField(
            model_name='bingocardextended',
            name='total_wins',
            field=models.IntegerField(default=0, help_text='Total de veces que ha ganado'),
        ),
        migrations.AddField(
            model_name='bingosession',
            name='card_source',
            field=models.CharField(choices=[('generate', 'Generar nuevas cartas'), ('pack', 'Usar cartas de un pack'), ('player_cards', 'Jugadores usan sus propias cartas')], default='player_cards', help_text='Origen de las cartas para esta sesión', max_length=20),
        ),
        migrations.AlterField(
            model_name='bingocardextended',
            name='card_number',
            field=models.IntegerField(default=0, help_text='Número del cartón'),
        ),
        migrations.AlterField(
            model_name='bingosession',
            name='allow_card_reuse',
            field=models.BooleanField(default=False, help_text='[DEPRECATED] Permitir reutilizar cartones'),
        ),
        migrations.AlterField(
            model_name='bingosession',
            name='cards_generated',
            field=models.BooleanField(default=False, help_text='[DEPRECATED] Si los cartones ya fueron generados'),
        ),
        migrations.AlterField(
            model_name='bingosession',
            name='total_cards',
            field=models.IntegerField(default=100, help_text='[DEPRECATED] Cantidad total de cartones generados'),
        ),
        migrations.CreateModel(
            name='CardPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del pack (ej: Pack Clásico 75)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción del pack')),
                ('bingo_type', models.CharField(choices=[('75', '75 bolas'), ('85', '85 bolas'), ('90', '90 bolas')], help_text='Tipo de bingo', max_length=10)),
                ('total_cards', models.IntegerField(default=100, help_text='Cantidad total de cartas en el pack')),
                ('cards_generated', models.BooleanField(default=False, help_text='Si las cartas ya fueron generadas')),
                ('price_per_card', models.DecimalField(decimal_places=2, default=0, help_text='Precio por carta (0 = gratuito)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Pack activo')),
                ('is_public', models.BooleanField(default=True, help_text='Visible para todos los jugadores')),
                ('category', models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Básico'), ('premium', 'Premium'), ('vip', 'VIP'), ('legacy', 'Legacy')], default='basic', help_text='Categoría del pack', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_packs', to='bingo.operator')),
            ],
            options={
                'verbose_name': 'Card Pack',
                'verbose_name_plural': 'Card Packs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bingocardextended',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='bingo.cardpack'),
        ),
        migrations.AddField(
            model_name='bingosession',
            name='card_pack',
            field=models.ForeignKey(blank=True, help_text="Pack de cartas a usar (solo si card_source='pack')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='bingo.cardpack'),
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('acquisition_type', models.CharField(choices=[('purchase', 'Compra'), ('gift', 'Regalo'), ('reward', 'Recompensa'), ('promotion', 'Promoción'), ('initial', 'Pack Inicial')], default='purchase', help_text='Tipo de adquisición', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio de compra', max_digits=10)),
                ('times_used', models.IntegerField(default=0, help_text='Veces que se ha usado')),
                ('times_won', models.IntegerField(default=0, help_text='Veces que ha ganado')),
                ('total_prizes', models.DecimalField(decimal_places=2, default=0, help_text='Total de premios ganados con esta carta', max_digits=10)),
                ('is_favorite', models.BooleanField(default=False, help_text='Carta marcada como favorita')),
                ('nickname', models.CharField(blank=True, help_text="Apodo personalizado (ej: 'Mi carta de la suerte')", max_length=50)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Última vez que se usó', null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='bingo.bingocardextended')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.cardpack')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cards', to='bingo.player')),
            ],
            options={
                'verbose_name': 'Player Card',
                'verbose_name_plural': 'Player Cards',
                'ordering': ['-is_favorite', '-times_won', '-acquired_at'],
                'unique_together': {('player', 'card')},
            },
        ),
        migrations.CreateModel(
            name='SessionCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('playing', 'Jugando'), ('won', 'Ganadora'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='active', help_text='Estado de la carta en esta sesión', max_length=20)),
                ('marked_numbers', models.JSONField(default=list, help_text='Números que han sido marcados en esta sesión')),
                ('is_winner', models.BooleanField(default=False, help_text='Es carta ganadora en esta sesión')),
                ('winning_patterns', models.JSONField(default=list, help_text='Patrones ganadores completados')),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto del premio ganado', max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_instances', to='bingo.bingocardextended')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cards', to='bingo.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cards', to='bingo.bingosession')),
            ],
            options={
                'verbose_name': 'Session Card',
                'verbose_name_plural': 'Session Cards',
                'ordering': ['-joined_at'],
                'unique_together': {('session', 'card', 'player')},
            },
        ),
    ]
